<?php
//https://www.codeigniter.com/userguide3/libraries/image_lib.html
//http://www.roytuts.com/upload-and-resize-image-using-codeigniter/
//http://www.webslesson.info/2016/11/codeigniter-tutorial-compress-and-resize-uploaded-image.html
//https://midpart.wordpress.com/2012/11/09/453/
//http://evanblack.com/blog/codeigniter-image-upload-and-resize/
//http://avenir.ro/codeigniter-tutorials/crop-resize-uploaded-images-in-codeigniter/
//==================================================
//http://avenir.ro/image_nation-codeigniter-library/
//==================================================
//http://www.roytuts.com/upload-and-resize-image-using-codeigniter/